language: emacs-lisp
sudo: false
cache:
- directories:
  - "$HOME/emacs"
matrix:
  fast_finish: true
  allow_failures:
  - env: EMACS_VERSION=snapshot
env:
  matrix:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.2
  - EMACS_VERSION=snapshot
  global:
    secure: yN1qbXxfPXcn0T5YIJSnhew/8NHskRzxHn7LauWpxo/Z4Yjb4kte8TIZ93XCfUmcJGEbkHF4wejgui7v09UrUv8tYZO8rUomn7pF6qTtziuwoIMvDdm8Jt4F6xvCUnTjw3gmlVZcJkWcnxVAZQitYdkEZPeTFWyjAGYZlxXhCVh05usBAhHEEwjBkQD4n8Z3O0U9Y553XGj7RqUteA3rnk46WxHpGXCwNmYHdEturZkbmfPqyD7oosstb5fwsZ4CtzgNxnu8o1B5vnk7jUv+fQVyXxxL/0MzfeqFLUjDZH2TwOl0N+/m1Gp41K+TiHpwuHgTw2rvDlikn0Z4EMuDPYyMv2P9SJW48ZtACNhOJ09H8BnrvjG6lxpayJbxmAdXgsMyEO63UhwHV7rnl9BRJ5mFX++wSnnV8G5u/Yp92rIW2Kxj5JoYKcy7/SF+7zFQq7ai+uVGPqseYg+k4BhZgpSgbofLuBKt9KZKMgDqS8bLjh1bvWG8STtN6dHIKLEz746p2MEINjJbg0ysEADujmwWsFdvqr584hRceAtkqynXHgpRh66BoB4a4d8dMUWstzQr9werEGbDcuQeJ8HFcpSirR3+Sw7LbjScHC/toKVG7vty6M9vHWlB1iAEUDps96nvpdAwPlhEL/rcRO1zqrm/OhlunRSpxh0V/dXcj1g=

before_install:
- export PATH="$HOME/bin:$PATH"
- wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
- make -f emacs-travis.mk install_emacs
- make -f emacs-travis.mk install_cask
install:
- cask install
script:
- cask exec ert-runner
notifications:
  email:
    on_success: never
    on_failure: change
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/b1163bae60c65660fbd2
    on_success: change
    on_failure: always
    on_start: never
